# Generated by Django 5.1 on 2025-05-07 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('puntos', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('esferico_od_lejana', models.CharField(blank=True, max_length=10)),
                ('cilindrico_od_lejana', models.CharField(blank=True, max_length=10)),
                ('eje_od_lejana', models.CharField(blank=True, max_length=10)),
                ('esferico_oi_lejana', models.CharField(blank=True, max_length=10)),
                ('cilindrico_oi_lejana', models.CharField(blank=True, max_length=10)),
                ('eje_oi_lejana', models.CharField(blank=True, max_length=10)),
                ('esferico_od_cercana', models.CharField(blank=True, max_length=10)),
                ('cilindrico_od_cercana', models.CharField(blank=True, max_length=10)),
                ('eje_od_cercana', models.CharField(blank=True, max_length=10)),
                ('esferico_oi_cercana', models.CharField(blank=True, max_length=10)),
                ('cilindrico_oi_cercana', models.CharField(blank=True, max_length=10)),
                ('eje_oi_cercana', models.CharField(blank=True, max_length=10)),
                ('esferico_od_contacto', models.CharField(blank=True, max_length=10)),
                ('cilindrico_od_contacto', models.CharField(blank=True, max_length=10)),
                ('eje_od_contacto', models.CharField(blank=True, max_length=10)),
                ('esferico_oi_contacto', models.CharField(blank=True, max_length=10)),
                ('cilindrico_oi_contacto', models.CharField(blank=True, max_length=10)),
                ('eje_oi_contacto', models.CharField(blank=True, max_length=10)),
                ('adicion', models.CharField(blank=True, max_length=100)),
                ('tipo_lente_contacto', models.CharField(blank=True, max_length=100)),
                ('monofocal', models.BooleanField(default=False)),
                ('multifocal', models.BooleanField(default=False)),
                ('bifocal', models.BooleanField(default=False)),
                ('por_separado', models.BooleanField(default=False)),
                ('organico', models.BooleanField(default=False)),
                ('antirreflejo', models.BooleanField(default=False)),
                ('uvx', models.BooleanField(default=False)),
                ('fotocromatico', models.BooleanField(default=False)),
                ('ref_armazon', models.CharField(blank=True, max_length=100)),
                ('ref_cristal', models.CharField(blank=True, max_length=100)),
                ('total_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entrega', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dip', models.CharField(blank=True, max_length=20)),
                ('naso_pupilar_od', models.CharField(blank=True, max_length=20)),
                ('naso_pupilar_oi', models.CharField(blank=True, max_length=20)),
                ('alt', models.CharField(blank=True, max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
